
name-template: 'v$NEXT_MINOR_VERSION 🌈'
tag-template: 'v$NEXT_MINOR_VERSION'

categories:
  - title: 🚀 主要功能和改进
    labels:
      - 'feature'
      - 'enhancement'
  - title: 🐛 Bug 修复
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 维护'
    label: 'chore'
  - title: 📝 文档更新
    labels:
      - 'documentation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## 变更日志

  $CHANGES
