name-template: 'v$NEXT_MINOR_VERSION 🌈'
tag-template: 'v$NEXT_MINOR_VERSION'

template: |
  ## 变更日志 👀

  $CHANGES
categories:
  - title: 🚀 功能和改进
    labels:
      - 'feature'
      - 'enhancement'
  - title: 🐛 Bug 修复
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 维护'
    label: 'chore'
  - title: 📖 文档
    labels:
      - 'documentation'
  - title: 🧪 测试
    labels:
      - 'test'
  - title: 📝 其他
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch