name: CI

on:
#  PR 合并到 main 分支
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
  push:
#    推送的标签以 v 开头时触发
    tags: [ v* ]
#    手动触发工作流
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4
  publish:
    name: Publish release
    needs: [ ci ]
    # 当事件不是 PR 且引用是标签以 v 开头时触发
    if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-22.04
    steps:
      # 提取版本号并设置为环境变量
      - name: Extract version from tag
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed 's|refs/tags/v||')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      # 发布版本说明
      - name: Publish release notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          publish: true
          name: "v${{ env.VERSION }}"
          tag: "v${{ env.VERSION }}"
          version: "v${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}