name: ci

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
      COREPACK_DEFAULT_TO_LATEST: 0
    steps:
      - uses: actions/checkout@v4