name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
      COREPACK_DEFAULT_TO_LATEST: 0
    steps:
      - uses: actions/checkout@v4
      # 发布Release
      - name: Update Release Drafter
        if: ${{ github.ref == 'refs/heads/main' && success() }}
        id: last_release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release Version Info
        run:
          echo "Release version is:" ${{ steps.last_release.outputs.tag_name }}